name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev
    - name: make
      run: make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: minesweeper_linux
        path: minesweeper
